spring.application.name=Taskify
server.port=${PORT:8082}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/taskify?createDatabaseIfNotExist=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secretKey= ${JWT_SECRET_KEY:this_is_a_default_secret_key_just_for_local_testing_purposes}
jwt.refresh-expiration-ms=${JWT_REFRESH_EXPIRATION_MS:604800000}
server.forward-headers-strategy=framework
server.servlet.context-path=/api